In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import sqlite3 as sql

In [2]:
#read in the data

In [3]:
dems = pd.read_excel(
   '/Users/georgehayward/Hayward Dropbox/George Hayward/Hayward Data Science/GrandStreetDems/data_lab/grand_street_dems/data/2026-03-01/VoterData_AssemblyDistrict65.xlsx'
)

In [4]:
dems.head(10)

,VSN,LastName,FirstName,MiddleInitial,NameSuffix,Borough,RegStreetNumber,RegStreetName,RegUnitNumber,RegCity,...,JudicialDistrict,PhoneNumber,EmailAddress,BirthDate,RegistrationDate,StatusCode,PoliticalParty,VoterType,EffectiveStatusChangeDate,LastElectionVotedIn
0,414668071,JOW,ALEXANDER,NaN,NaN,Manhattan,20,BROAD STREET,NaN,NEW YORK,...,1,NaN,ALEXANDER.JOW@GMAIL.COM,19950714,20241001,A,DEM,R,NaN,20241105.0
1,414424984,RAMAKRISHNAN,HARI,NaN,NaN,Manhattan,20,BROAD STREET,NaN,NEW YORK,...,1,2247176336,HARIS500@GMAIL.COM,20000805,20230922,A,DEM,R,20230922.0,20251104.0
2,414325345,SINCLAIR,CAITLIN,A,NaN,Manhattan,20,BROAD STREET,NaN,NEW YORK,...,1,NaN,NaN,19960316,20221108,A,REP,R,20221108.0,NaN
3,414887521,SAMUELSEN,HALEY,N,NaN,Manhattan,20,BROAD STREET,1001,NEW YORK,...,1,281-660-7394,HSAMUELSEN@COMCAST.NET,20010618,20250422,A,REP,R,NaN,NaN
4,413143937,RAHMAN,GELECIA,A,NaN,Manhattan,20,BROAD STREET,1002,NEW YORK,...,1,NaN,NaN,19840720,20180730,A,DEM,R,20240507.0,20250624.0
5,414390001,KONTYKO,KAITLIN,A,NaN,Manhattan,20,BROAD STREET,1006,NEW YORK,...,1,NaN,kakontyko@gmail.com,19881025,20230614,A,DEM,R,NaN,20251104.0
6,414389887,YU,ALBERT,S,NaN,Manhattan,20,BROAD STREET,1006,NEW YORK,...,1,NaN,albertyu17@gmail.com,19890107,20230614,A,DEM,R,NaN,20251104.0
7,414515985,SHEU,ANDREW,J,NaN,Manhattan,20,BROAD STREET,1012,NEW YORK,...,1,NaN,NaN,19900613,20240402,A,BLK,R,NaN,NaN
8,412822698,HAJJAR,ZACKARY,G,NaN,Manhattan,20,BROAD STREET,1015,NEW YORK,...,1,917-626-5625,zhajjar@yahoo.com,19990531,20170609,A,DEM,R,20170612.0,20241105.0
9,414134286,PANGILINAN,ADRIAN,B,NaN,Manhattan,20,BROAD STREET,1015,NEW YORK,...,1,201-654-5408,ADRIAN.PANGILINAN@GMAIL.COM,19941125,20210924,A,DEM,R,NaN,20251104.0

In [11]:
dems.dtypes

VSN                           object
LastName                      object
FirstName                     object
MiddleInitial                 object
NameSuffix                    object
Borough                       object
RegStreetNumber               object
RegStreetName                 object
RegUnitNumber                 object
RegCity                       object
RegZipCode                     int64
MailingAddress1               object
MailingAddress2               object
MailingAddress3               object
MailingAddress4               object
AssemblyDistrict               int64
ElectionDistrict               int64
CongressionalDistrict          int64
CouncilDistrict                int64
SenateDistrict                 int64
CivilCourtDistrict             int64
JudicialDistrict               int64
PhoneNumber                   object
EmailAddress                  object
BirthDate                      int64
RegistrationDate               int64
StatusCode                    object
PoliticalParty                object
VoterType                     object
EffectiveStatusChangeDate    float64
LastElectionVotedIn          float64
dtype: object

In [5]:
for i in dems.columns:
    print(i)

VSN
LastName
FirstName
MiddleInitial
NameSuffix
Borough
RegStreetNumber
RegStreetName
RegUnitNumber
RegCity
RegZipCode
MailingAddress1
MailingAddress2
MailingAddress3
MailingAddress4
AssemblyDistrict
ElectionDistrict
CongressionalDistrict
CouncilDistrict
SenateDistrict
CivilCourtDistrict
JudicialDistrict
PhoneNumber
EmailAddress
BirthDate
RegistrationDate
StatusCode
PoliticalParty
VoterType
EffectiveStatusChangeDate
LastElectionVotedIn

In [6]:
conn = sql.connect("gsd_dems_1.db")

In [7]:
dems.to_sql("gsdems",conn,if_exists='replace',index=False)

85824

In [8]:
gsd_dems_youth_select_1 = pd.read_sql_query("""
select * from gsdems 
where 1=1
and PoliticalParty in ('DEM', 'WOR')
and EmailAddress is not NULL
and BirthDate >= 20000000 -- this is our proxy for born after 2000 (so under 25)
and ElectionDistrict in (013,014,023,024,025,026,028,029,030,031,032,033,041,046,047,048,052,053,054,067)
;
""", conn)
gsd_dems_youth_select_1

,VSN,LastName,FirstName,MiddleInitial,NameSuffix,Borough,RegStreetNumber,RegStreetName,RegUnitNumber,RegCity,...,JudicialDistrict,PhoneNumber,EmailAddress,BirthDate,RegistrationDate,StatusCode,PoliticalParty,VoterType,EffectiveStatusChangeDate,LastElectionVotedIn
0,414962243,RAMANATHAN,ANJALI,None,None,Manhattan,225,CHERRY STREET,16G,NEW YORK,...,1,6506830165,ANJALI@RAMANATHAN.UK,20021128,20250613,A,DEM,R,NaN,20250624.0
1,413393408,ORTIZ,JULIE,A,None,Manhattan,225,CHERRY STREET,22E,NEW YORK,...,1,6463191280,JULIE.FLORES.ORTIZ@GMAIL.COM,20000628,20190215,A,WOR,R,20190215.0,20251104.0
2,414935311,GRAJEDA,CARLOS,F,None,Manhattan,225,CHERRY STREET,39E,NEW YORK,...,1,9569490407,CARLOS.F.GRAJEDA@GMAIL.COM,20000526,20250611,A,DEM,R,NaN,20251104.0
3,414247097,HSU,ABRAHAM,L,None,Manhattan,225,CHERRY STREET,51B,NEW YORK,...,1,None,ABRAHAMHSU1220@ICLOUD.COM,20001220,20220802,A,DEM,R,20220802.0,20251104.0
4,415052433,LIN,SAMANTHA,None,None,Manhattan,225,CHERRY STREET,53F,NEW YORK,...,1,None,LINSAMANTHA123@GMAIL.COM,20020605,20251001,A,DEM,R,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1026,414476677,ANABITARTE MOGNA,ANDREA,None,None,Manhattan,10,RUTGERS STREET,2D,NEW YORK,...,1,9176010718,andyanabitarte@gmail.com,20040802,20240129,A,DEM,R,20240916.0,20241105.0
1027,414903548,WU,AARON,F,None,Manhattan,10,RUTGERS STREET,3G,NEW YORK,...,1,6266891701,AARONWU219@GMAIL.COM,20010219,20250521,A,DEM,R,20250521.0,20251104.0
1028,414971619,BISHT,KHUSHI,None,None,Manhattan,10,RUTGERS STREET,5D,NEW YORK,...,1,5163051158,KHUSHIBISHT16@GMAIL.COM,20011216,20250614,A,DEM,R,NaN,20251104.0
1029,414915421,ZHANG,ANNA,None,None,Manhattan,10,RUTGERS STREET,5D,NEW YORK,...,1,617-795-6605,ANNAYZHANG.2@GMAIL.COM,20011228,20250605,A,DEM,R,NaN,20251104.0
1030,414652158,SANI,NIL,None,None,Manhattan,10,RUTGERS STREET,6B,NEW YORK,...,1,310-561-7133,NILSANTITR@GMAIL.COM,20030319,20240920,A,DEM,R,20240920.0,20251104.0

In [9]:
gsd_dems_youth_select_1.to_csv('gsd_dems_youth_select_1.csv', index=False, encoding='utf-8')

In [10]:
gsd_dems_youth_activist = pd.read_sql_query("""
select * from gsdems 
where 1=1
and PoliticalParty in ('DEM', 'WOR')
and EmailAddress is not NULL
and BirthDate >= 20000000 -- this is our proxy for born after 2000 (so under 25)
and ElectionDistrict in (013,014,023,024,025,026,028,029,030,031,032,033,041,046,047,048,052,053,054,067)
and PR20240625 != 'N' --PR20240625 means 2024 Primary; 'N' means didn't vote
;
""", conn)
gsd_dems_youth_activist

DatabaseError: Execution failed on sql '
select * from gsdems
where 1=1
and PoliticalParty in ('DEM', 'WOR')
and EmailAddress is not NULL
and BirthDate >= 20000000 -- this is our proxy for born after 2000 (so under 25)
and ElectionDistrict in (013,014,023,024,025,026,028,029,030,031,032,033,041,046,047,048,052,053,054,067)
and PR20240625 != 'N' --PR20240625 means 2024 Primary; 'N' means didn't vote
;
': no such column: PR20240625

In [15]:
gsd_dems_youth_activist.to_csv('gsd_dems_youth_activist.csv', index=False, encoding='utf-8')

NameError: name 'gsd_dems_youth_activist' is not defined

In [16]:
#voted in 2025 mamdani primary
gsd_dems_youth_voted_in_mamdani_general = pd.read_sql_query("""
select * from gsdems 
where 1=1
and PoliticalParty in ('DEM', 'WOR')
and EmailAddress is not NULL
and BirthDate >= 20000000 -- this is our proxy for born after 2000 (so under 25)
and ElectionDistrict in (013,014,023,024,025,026,028,029,030,031,032,033,041,046,047,048,052,053,054,067)
--and PR20240625 != 'N' --PR20240625 means 2024 Primary; 'N' means didn't vote
-- ^^ no longer in the data file
and LastElectionVotedIn = 20251104
;
""", conn)
gsd_dems_youth_voted_in_mamdani_general

,VSN,LastName,FirstName,MiddleInitial,NameSuffix,Borough,RegStreetNumber,RegStreetName,RegUnitNumber,RegCity,...,JudicialDistrict,PhoneNumber,EmailAddress,BirthDate,RegistrationDate,StatusCode,PoliticalParty,VoterType,EffectiveStatusChangeDate,LastElectionVotedIn
0,413393408,ORTIZ,JULIE,A,None,Manhattan,225,CHERRY STREET,22E,NEW YORK,...,1,6463191280,JULIE.FLORES.ORTIZ@GMAIL.COM,20000628,20190215,A,WOR,R,20190215.0,20251104.0
1,414935311,GRAJEDA,CARLOS,F,None,Manhattan,225,CHERRY STREET,39E,NEW YORK,...,1,9569490407,CARLOS.F.GRAJEDA@GMAIL.COM,20000526,20250611,A,DEM,R,NaN,20251104.0
2,414247097,HSU,ABRAHAM,L,None,Manhattan,225,CHERRY STREET,51B,NEW YORK,...,1,None,ABRAHAMHSU1220@ICLOUD.COM,20001220,20220802,A,DEM,R,20220802.0,20251104.0
3,413831104,POWER,JAMES,A,None,Manhattan,225,CHERRY STREET,53H,NEW YORK,...,1,516-497-6592,jaogz2001@gmail.com,20010523,20200826,A,DEM,R,NaN,20251104.0
4,414589934,MCDANIEL,LUCIOUS,C,IV,Manhattan,225,CHERRY STREET,65C,NEW YORK,...,1,8323417603,LUCIOUS4@ICLOUD.COM,20000807,20240806,A,DEM,R,20240806.0,20251104.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497,414763516,DACY,ISAAC,R,None,Manhattan,10,RUTGERS STREET,2B,NEW YORK,...,1,212-729-9814,ISAACRDACY@GMAIL.COM,20001017,20241026,A,DEM,R,NaN,20251104.0
498,414903548,WU,AARON,F,None,Manhattan,10,RUTGERS STREET,3G,NEW YORK,...,1,6266891701,AARONWU219@GMAIL.COM,20010219,20250521,A,DEM,R,20250521.0,20251104.0
499,414971619,BISHT,KHUSHI,None,None,Manhattan,10,RUTGERS STREET,5D,NEW YORK,...,1,5163051158,KHUSHIBISHT16@GMAIL.COM,20011216,20250614,A,DEM,R,NaN,20251104.0
500,414915421,ZHANG,ANNA,None,None,Manhattan,10,RUTGERS STREET,5D,NEW YORK,...,1,617-795-6605,ANNAYZHANG.2@GMAIL.COM,20011228,20250605,A,DEM,R,NaN,20251104.0
501,414652158,SANI,NIL,None,None,Manhattan,10,RUTGERS STREET,6B,NEW YORK,...,1,310-561-7133,NILSANTITR@GMAIL.COM,20030319,20240920,A,DEM,R,20240920.0,20251104.0

In [17]:
gsd_dems_youth_voted_in_mamdani_general.to_csv('gsd_dems_youth_voted_in_mamdani_primary.csv', index=False, encoding='utf-8')

In [32]:
gsd_dems_youth_missed_2024_primary = pd.read_sql_query("""
select * from gsdems 
where 1=1
and PoliticalParty in ('DEM', 'WOR')
and EmailAddress is not NULL
and BirthDate >= 20000000 -- this is our proxy for born after 2000 (so under 25)
and ElectionDistrict in (013,014,023,024,025,026,028,029,030,031,032,033,041,046,047,048,052,053,054,067)
and PR20240625 = 'N' --PR20240625 means 2024 Primary; 'N' means didn't vote
;
""", conn)
gsd_dems_youth_missed_2024_primary

,VSN,LastName,FirstName,MiddleInitial,NameSuffix,Borough,RegStreetNumber,RegStreetName,RegUnitNumber,RegCity,...,GE20191105,PR20190625,GE20181106,PR20180913,GE20171107,PR20170912,GE20161108,PR20160913,GE20151103,PR20150910
0,413651560,BRIK,CAMILA,C,None,Manhattan,225,CHERRY STREET,37C,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
1,414247097,HSU,ABRAHAM,L,None,Manhattan,225,CHERRY STREET,51B,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
2,413831104,POWER,JAMES,A,None,Manhattan,225,CHERRY STREET,53H,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
3,414527624,FANG,CHENMING,None,None,Manhattan,225,CHERRY STREET,59E,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
4,413151603,MENDEZ STERLING,CHARISMA,D,None,Manhattan,227,CHERRY STREET,11K,NEW YORK,...,N,N,"R,R","R,R",N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
624,414105743,YOUNG,CLARA,None,None,Manhattan,268,EAST BROADWAY,A1501,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
625,414213025,BERG,OLIVIA,F,None,Manhattan,268,EAST BROADWAY,A1604,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
626,414401182,WONG,KATELIN,None,None,Manhattan,268,EAST BROADWAY,A1705,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
627,414191546,CROWLEY,LEA,J,None,Manhattan,268,EAST BROADWAY,A401,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
628,414521485,ROSENBERG,ALICE,L,None,Manhattan,268,EAST BROADWAY,A901,NEW YORK,...,N,N,N,N,N,N,N,N,N,N

In [33]:
gsd_dems_youth_missed_2024_primary.to_csv('gsd_dems_youth_missed_2024_primary.csv', index=False, encoding='utf-8')