In [7]:
import pandas as pd
from matplotlib import pyplot as plt
import sqlite3 as sql

In [8]:
#read in the data

In [9]:
dems = pd.read_csv(
    '/data/2025-11-15/VoterData_AD65_withHistory.xlsm - Voter Data.csv',
    low_memory=False
)

In [10]:
dems.head(10)

,VSN,LastName,FirstName,MiddleInitial,NameSuffix,Borough,RegStreetNumber,RegStreetName,RegUnitNumber,RegCity,...,GE20191105,PR20190625,GE20181106,PR20180913,GE20171107,PR20170912,GE20161108,PR20160913,GE20151103,PR20150910
0,414592441,HERWIG,MARK,F,NaN,Manhattan,20,BROAD STREET,NaN,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
1,414668071,JOW,ALEXANDER,NaN,NaN,Manhattan,20,BROAD STREET,NaN,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
2,414686967,VAYGENSBERG,ROSS,NaN,NaN,Manhattan,20,BROAD STREET,NaN,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
3,413143937,RAHMAN,GELECIA,A,NaN,Manhattan,20,BROAD STREET,1002,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
4,414390001,KONTYKO,KAITLIN,A,NaN,Manhattan,20,BROAD STREET,1006,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
5,414389887,YU,ALBERT,S,NaN,Manhattan,20,BROAD STREET,1006,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
6,414515985,SHEU,ANDREW,J,NaN,Manhattan,20,BROAD STREET,1012,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
7,412822698,HAJJAR,ZACKARY,G,NaN,Manhattan,20,BROAD STREET,1015,NEW YORK,...,N,N,"R,R",N,N,N,N,N,N,N
8,414134286,PANGILINAN,ADRIAN,B,NaN,Manhattan,20,BROAD STREET,1015,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
9,414118313,CLARKE,JOHN,Q,NaN,Manhattan,20,BROAD STREET,1019,NEW YORK,...,N,N,N,N,N,N,N,N,N,N

In [13]:
for i in dems.columns:
    print(i)

VSN
LastName
FirstName
MiddleInitial
NameSuffix
Borough
RegStreetNumber
RegStreetName
RegUnitNumber
RegCity
RegZipCode
MailingAddress1
MailingAddress2
MailingAddress3
MailingAddress4
AssemblyDistrict
ElectionDistrict
CongressionalDistrict
CouncilDistrict
SenateDistrict
CivilCourtDistrict
JudicialDistrict
PhoneNumber
EmailAddress
BirthDate
RegistrationDate
StatusCode
PoliticalParty
VoterType
EffectiveStatusChangeDate
LastElectionVotedIn
GE20241105
PR20240625
GE20231107
PR20230627
GE20221108
PR20220628
GE20211102
PR20210622
GE20201103
PR20200623
GE20191105
PR20190625
GE20181106
PR20180913
GE20171107
PR20170912
GE20161108
PR20160913
GE20151103
PR20150910

In [11]:
conn = sql.connect("gsd_dems_1.db")

In [12]:
dems.to_sql("gsdems",conn,if_exists='replace',index=False)

86366

In [27]:
gsd_dems_youth_select_1 = pd.read_sql_query("""
select * from gsdems 
where 1=1
and PoliticalParty in ('DEM', 'WOR')
and EmailAddress is not NULL
and BirthDate >= 20000000 -- this is our proxy for born after 2000 (so under 25)
and ElectionDistrict in (013,014,023,024,025,026,028,029,030,031,032,033,041,046,047,048,052,053,054,067)
;
""", conn)
gsd_dems_youth_select_1

,VSN,LastName,FirstName,MiddleInitial,NameSuffix,Borough,RegStreetNumber,RegStreetName,RegUnitNumber,RegCity,...,GE20191105,PR20190625,GE20181106,PR20180913,GE20171107,PR20170912,GE20161108,PR20160913,GE20151103,PR20150910
0,413651560,BRIK,CAMILA,C,None,Manhattan,225,CHERRY STREET,37C,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
1,414247097,HSU,ABRAHAM,L,None,Manhattan,225,CHERRY STREET,51B,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
2,413831104,POWER,JAMES,A,None,Manhattan,225,CHERRY STREET,53H,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
3,414527624,FANG,CHENMING,None,None,Manhattan,225,CHERRY STREET,59E,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
4,413151603,MENDEZ STERLING,CHARISMA,D,None,Manhattan,227,CHERRY STREET,11K,NEW YORK,...,N,N,"R,R","R,R",N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,413690506,BRENNAN,ALICE,G,None,Manhattan,268,EAST BROADWAY,A1601,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
656,414213025,BERG,OLIVIA,F,None,Manhattan,268,EAST BROADWAY,A1604,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
657,414401182,WONG,KATELIN,None,None,Manhattan,268,EAST BROADWAY,A1705,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
658,414191546,CROWLEY,LEA,J,None,Manhattan,268,EAST BROADWAY,A401,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
659,414521485,ROSENBERG,ALICE,L,None,Manhattan,268,EAST BROADWAY,A901,NEW YORK,...,N,N,N,N,N,N,N,N,N,N

In [28]:
gsd_dems_youth_select_1.to_csv('gsd_dems_youth_select_1.csv', index=False, encoding='utf-8')

In [29]:
gsd_dems_youth_activist = pd.read_sql_query("""
select * from gsdems 
where 1=1
and PoliticalParty in ('DEM', 'WOR')
and EmailAddress is not NULL
and BirthDate >= 20000000 -- this is our proxy for born after 2000 (so under 25)
and ElectionDistrict in (013,014,023,024,025,026,028,029,030,031,032,033,041,046,047,048,052,053,054,067)
and PR20240625 != 'N' --PR20240625 means 2024 Primary; 'N' means didn't vote
;
""", conn)
gsd_dems_youth_activist

,VSN,LastName,FirstName,MiddleInitial,NameSuffix,Borough,RegStreetNumber,RegStreetName,RegUnitNumber,RegCity,...,GE20191105,PR20190625,GE20181106,PR20180913,GE20171107,PR20170912,GE20161108,PR20160913,GE20151103,PR20150910
0,414093824,LIN,CHRISTINA,None,None,Manhattan,201,MADISON STREET,17,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
1,414328367,JUSTE,LEAH,S,None,Manhattan,55,RUTGERS STREET,8C,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
2,413676168,LI,SIONA,M,None,Manhattan,265,CHERRY STREET,2G,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
3,413531567,CHAN,ALEXANDRA,N,None,Manhattan,275,SOUTH STREET,9D,NEW YORK,...,"R,A",N,N,N,N,N,N,N,N,N
4,414115731,KRAMNICK,SAMUEL,O,None,Manhattan,473,FRANKLIN D ROOSEVELT DRIVE,K304,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
5,414100699,SEGAL,GABRIEL,None,None,Manhattan,475,FRANKLIN D ROOSEVELT DRIVE,301,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
6,413765413,PARKER,KELLY,R,None,Manhattan,570,GRAND STREET,H1105,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
7,414426099,VARENIK,TALIA,G,None,Manhattan,500A,GRAND STREET,2B,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
8,413779949,POLEN,ALICE,E,None,Manhattan,500A,GRAND STREET,4A,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
9,414483220,PETERSSON,MINTESINOT,C,None,Manhattan,500C,GRAND STREET,9C,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
10,414083508,GLEDHILL,THOMAS,J,None,Manhattan,530,GRAND STREET,E3E,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
11,413594341,GINN,THOMAS,R,None,Manhattan,530,GRAND STREET,F5F,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
12,414491460,REBOLLEDO,PAZ,I,None,Manhattan,530D,GRAND STREET,3E,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
13,414235000,QUEZADA,SOLANA,A,None,Manhattan,530D,GRAND STREET,8E,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
14,414050315,BECKER,MICHAEL,R,None,Manhattan,530F,GRAND STREET,11H,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
15,414258303,SO,EMMA,J,None,Manhattan,550,GRAND STREET,G6B,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
16,414535997,MEDOWS,PHILIP-DAVID,None,None,Manhattan,550H,GRAND STREET,1E,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
17,414463735,SPIES,ERIC,T,None,Manhattan,550H,GRAND STREET,7F,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
18,414387538,GSELL,BESS,L,None,Manhattan,173,EAST BROADWAY,C1LBBY,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
19,414387972,GSELL,SAM,A,None,Manhattan,175,EAST BROADWAY,C1,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
20,414181411,LU,BRENDAN,J,None,Manhattan,189,EAST BROADWAY,3B,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
21,414260888,IBANEZ- ROUHE,INEZ,M,None,Manhattan,210,EAST BROADWAY,H401,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
22,414206788,APPELBAUM,ELIZABETH,E,None,Manhattan,212,EAST BROADWAY,G204,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
23,414562072,FELL,CORNELIA,R,None,Manhattan,383,GRAND STREET,M1007,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
24,413185011,ONO,NICHOLAS,K,None,Manhattan,383,GRAND STREET,M1106,NEW YORK,...,N,N,"R,R",N,N,N,N,N,N,N
25,414130996,HARTRAY,LUCIA,C,None,Manhattan,385,GRAND STREET,L2006,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
26,413088362,RAHMAN,MAHIR,S,None,Manhattan,160,ALLEN STREET,20,NEW YORK,...,"R,Y",N,"R,R","R,R",N,N,N,N,N,N
27,414353558,CARROLL THOMPSON,MOLLY,E,None,Manhattan,453,FRANKLIN D ROOSEVELT DRIVE,C407,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
28,414305820,JACOB,ANNA,None,None,Manhattan,577,GRAND STREET,302,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
29,414237612,CHAN,VIVIAN,None,None,Manhattan,14,ORCHARD STREET,6D,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
30,413690506,BRENNAN,ALICE,G,None,Manhattan,268,EAST BROADWAY,A1601,NEW YORK,...,N,N,N,N,N,N,N,N,N,N

In [30]:
gsd_dems_youth_activist.to_csv('gsd_dems_youth_activist.csv', index=False, encoding='utf-8')

In [32]:
gsd_dems_youth_missed_2024_primary = pd.read_sql_query("""
select * from gsdems 
where 1=1
and PoliticalParty in ('DEM', 'WOR')
and EmailAddress is not NULL
and BirthDate >= 20000000 -- this is our proxy for born after 2000 (so under 25)
and ElectionDistrict in (013,014,023,024,025,026,028,029,030,031,032,033,041,046,047,048,052,053,054,067)
and PR20240625 = 'N' --PR20240625 means 2024 Primary; 'N' means didn't vote
;
""", conn)
gsd_dems_youth_missed_2024_primary

,VSN,LastName,FirstName,MiddleInitial,NameSuffix,Borough,RegStreetNumber,RegStreetName,RegUnitNumber,RegCity,...,GE20191105,PR20190625,GE20181106,PR20180913,GE20171107,PR20170912,GE20161108,PR20160913,GE20151103,PR20150910
0,413651560,BRIK,CAMILA,C,None,Manhattan,225,CHERRY STREET,37C,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
1,414247097,HSU,ABRAHAM,L,None,Manhattan,225,CHERRY STREET,51B,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
2,413831104,POWER,JAMES,A,None,Manhattan,225,CHERRY STREET,53H,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
3,414527624,FANG,CHENMING,None,None,Manhattan,225,CHERRY STREET,59E,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
4,413151603,MENDEZ STERLING,CHARISMA,D,None,Manhattan,227,CHERRY STREET,11K,NEW YORK,...,N,N,"R,R","R,R",N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
624,414105743,YOUNG,CLARA,None,None,Manhattan,268,EAST BROADWAY,A1501,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
625,414213025,BERG,OLIVIA,F,None,Manhattan,268,EAST BROADWAY,A1604,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
626,414401182,WONG,KATELIN,None,None,Manhattan,268,EAST BROADWAY,A1705,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
627,414191546,CROWLEY,LEA,J,None,Manhattan,268,EAST BROADWAY,A401,NEW YORK,...,N,N,N,N,N,N,N,N,N,N
628,414521485,ROSENBERG,ALICE,L,None,Manhattan,268,EAST BROADWAY,A901,NEW YORK,...,N,N,N,N,N,N,N,N,N,N

In [33]:
gsd_dems_youth_missed_2024_primary.to_csv('gsd_dems_youth_missed_2024_primary.csv', index=False, encoding='utf-8')